# -*- coding: utf-8 -*-
"""codenatio-predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOEerMB8g4d49G0rQIWJX2olilDrTSCF
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn import ensemble
from sklearn import tree

df = pd.read_csv("test.csv")

modelo = pd.read_pickle('modelo.pkl')

df[modelo['variaveis_categoricas']] = df[modelo['variaveis_categoricas']].fillna(-1).astype(str)
df[modelo['variaveis_numericas']] = df[modelo['variaveis_numericas']].fillna(-1)

df_onehot = pd.DataFrame(modelo['onehot'].transform(df[modelo['variaveis_categoricas']]), columns=modelo['onehot'].get_feature_names(modelo['variaveis_categoricas']))

df_res = pd.concat([df[modelo['variaveis_numericas']], df_onehot], axis=1, ignore_index=True)

print(df_res)

print(df_res.isna().sum())

print(df_res.isna().sum().sum())

predict = modelo['modelo'].predict(df_res[modelo['features']])

df_resultado = df[['NU_INSCRICAO']]
df_resultado['NU_NOTA_MT'] = predict

df_resultado

df_resultado.to_csv('answer.csv', index=False)

